feat: init typography
boostgrade/wtgt_gamma pull request #11
Opened 2022-01-19 17:26 UTC by NeoZ3p

[# Ссылка на задачу](https://github.com/boostgrade/wtgt_gamma/issues/2)
Задача #2 
# Что было сделано

- Установил шрифт Montserrat разных плотностей (normal, 500, 600, bold).
- Добавил установленные шрифты в pubspec.yaml.
- В файле lib>src>core>ui>res>typography>app_typography.dart добавил настройки шрифта по дизайну.

# Как проверить работу?

- На странице main_screen, в переменной _screens (1 элемент) виджету Text() добавить параметр style: AppTypography.(subtitle1 / headline2 / body1 / body2 / caption / label / promobold)

# Чек-лист

- ✅ Функциональность протестирована и работает корректно

2022-01-19 17:44 UTC, dkrutskikh requested changes

2022-01-19 17:44 UTC, dkrutskikh commented on CHANGELOG.md
> +* feat: app typography
@NeoZ3p перенеси запись к новой версии (пусть она будет ## Unreleased)

2022-01-19 17:46 UTC, NeoZ3p commented on CHANGELOG.md
> +* feat: app typography
@dkrutskikh сделала

2022-01-19 18:20 UTC, Veselchak-U commented
0) Не замечание, а плюс - стили именованы как в макете - это удобно для последующей вёрстки.
1) Стили в файле лучше сортировать в порядке возрастания или убывания размера шрифта и жирности, чтобы глазами быстро находить нужный.
2) Полагаю, что fontFamily лучше прописать где-то в одном месте на верхнем уровне, например в будущей цветовой теме ThemeData(fontFamily: 'Montserrat'), чем в каждом текстовом стиле.
3) Для регулировки жирности стиля думаю лучше использовать font-weight, чем fontFamily.
4) В стилях не учтёна высота строки "height" - в макетах она нестандартная, рекомендую для наглядности указывать в виде выражения: line-height / font-size.
5) "letterSpacing=0.08" не уверен, что в логических пикселях это равно макетному "0.005em" - могу ошибаться. Но если это считается по какой-то формуле, то лучше для наглядности вставить её в виде выражения, чтобы было видны значения из макета.
6) В стиле "body2" ошибка - не учтена жирность из макета.
7) На экране "ChooseDateAndCount" нашёл другой шрифт - "Raleway". Вопрос к дизайнеру - не ошибка ли это? Если нет, то нужно подключать ещё один шрифт.

2022-01-20 18:02 UTC, dkrutskikh requested changes

2022-01-20 18:02 UTC, dkrutskikh commented on pubspec.yaml
> +
@NeoZ3p странный перенос

2022-01-20 18:02 UTC, dkrutskikh commented on lib/src/core/ui/res/typography/fonts_test_widget.dart
> +class FontsTestWidget extends StatelessWidget {
@NeoZ3p нам точно этот виджет нужен в основной папке исходников?

2022-01-20 18:02 UTC, dkrutskikh commented on lib/src/core/ui/res/typography/app_typography.dart
> +  static TextStyle headline2 = TextStyle(
@NeoZ3p в целом неплохо, как мы будем поступать если нам нужен стиль шрифта с определенным цветом?

2022-01-20 21:08 UTC, NeoZ3p commented on pubspec.yaml
> +
<img width="916" alt="image" src="https://user-images.githubusercontent.com/72041941/150422266-bed9bb45-9b3f-4ce4-873c-b5c5af2af8e4.png">

2022-01-21 11:52 UTC, dkrutskikh requested changes

2022-01-21 11:52 UTC, dkrutskikh commented on lib/src/core/ui/messages/types/common_snackbar.dart
> +    return SnackBar(content: Text(message, ));
@NeoZ3p зачем нам это?

2022-01-21 13:56 UTC, beersheba commented on lib/src/core/ui/res/typography/app_typography.dart
> +  const AppTypography.headline2({
а где headline1?

2022-01-21 13:56 UTC, beersheba commented on lib/src/core/ui/res/typography/app_typography.dart
> +  const AppTypography.subtitle1({
если он всего один, зачем индекс?

2022-01-21 13:56 UTC, beersheba commented on lib/src/core/ui/res/typography/app_typography.dart
> +  const AppTypography.body1({
почему бы не поместить его рядом с body2?

2022-01-21 14:09 UTC, NeoZ3p commented on lib/src/core/ui/messages/types/common_snackbar.dart
> +    return SnackBar(content: Text(message, ));
@dkrutskikh Убрал, даже не заметил :о

2022-01-21 14:33 UTC, loopnyapy approved these changes

2022-01-21 19:08 UTC, dkrutskikh approved these changes

2022-01-21 19:08 UTC, beersheba approved these changes

2022-01-21 19:17 UTC, merged