Interceptor
boostgrade/wtgt_gamma pull request #12
Opened 2022-01-20 15:28 UTC by beersheba

# Ссылка на задачу
Задача #4 

# Что было сделано

Добавил новые константы для ошибок запросов и их обработку в класс ServerErrorMapper.
Добавил Interceptor, использующий ServerErrorMapper и реагирующий на ошибки, согласно задаче.

# Как проверить работу?

Класс ServerErrorMapper может быть протестирован с помощью
test/api/server_error_mapper_test.dart

# Чек-лист

- [ ] Функциональность протестирована и работает корректно

2022-01-20 20:08 UTC, Veselchak-U commented
Замечания по файлу lib/src/core/services/network/dio/error_code_interceptor.dart 
1) Сокращения в именовании переменных: "exc" - не сразу понял, что это за сущность. "err" тоже можно для порядка написать полным именем.
2) Думаю это условие здесь не нужно: "if (err.response != null)". Процедура ServerErrorMapper.fromDioError(error) допускает null-response и в будущем может изменить свою логику, допустим определять необходимость перезапроса токена не только по коду ошибки. Т.е. в данном случае идентификация ошибки это не зона ответственности интерцептора.
3) Как я понял общую логику интерцепторов, переопределяемая функция onError() должна заканчиваться "handler.next(err)" или "reject.next(err)". Или можно использовать обёртку InterceptorsWrapper() в которой это уже есть.
4) Как я понял, задача стоит обработать только 400 и 401 коды, т.обр. только для них нужно делать "throw exc". Для остальных ошибок ничего не делаем.
5) IMHO этот импорт избыточен - 'package:flutter/cupertino.dart';  Для debugPrint достаточно  'package:flutter/foundation.dart'.

2022-01-21 13:29 UTC, beersheba commented
> Замечания по файлу lib/src/core/services/network/dio/error_code_interceptor.dart
> 
> 1. Сокращения в именовании переменных: "exc" - не сразу понял, что это за сущность. "err" тоже можно для порядка написать полным именем.

Я здесь использовал существующие имена - exc [из тестов,](https://github.com/boostgrade/wtgt_gamma/blob/8544a771404869fea0573db63613cd2da41f2ef5/test/api/server_error_mapper_test.dart#L31) err из спецификации [Dio](https://github.com/flutterchina/dio/blob/0e12e0198f5cd0bdd7992a1f0c529f203ba3385c/dio/lib/src/interceptor.dart#L302)

> 2. Думаю это условие здесь не нужно: "if (err.response != null)". Процедура ServerErrorMapper.fromDioError(error) допускает null-response и в будущем может изменить свою логику, допустим определять необходимость перезапроса токена не только по коду ошибки. Т.е. в данном случае идентификация ошибки это не зона ответственности интерцептора.
> 3. Как я понял общую логику интерцепторов, переопределяемая функция onError() должна заканчиваться "handler.next(err)" или "reject.next(err)". Или можно использовать обёртку InterceptorsWrapper() в которой это уже есть.
> 4. Как я понял, задача стоит обработать только 400 и 401 коды, т.обр. только для них нужно делать "throw exc". Для остальных ошибок ничего не делаем.
> 5. IMHO этот импорт избыточен - 'package:flutter/cupertino.dart';  Для debugPrint достаточно  'package:flutter/foundation.dart'.

Поправил.

Если можно, оставляй комментарии под кодом.

2022-01-21 19:44 UTC, NeoZ3p commented on lib/src/core/services/network/dio/error_code_interceptor.dart
> +    } else if (exc is ImageSoLargeException) {
Я бы делал без конструкций else if, а только if. Лично для меня так выражения становится более читабельным

if (exc is UnauthorizedException) throw exc;
if (exc is ImageSoLargeException) throw exc;

handler.next(err)

2022-01-21 19:45 UTC, NeoZ3p reviewed
Всё ок!

2022-01-21 19:55 UTC, NeoZ3p approved these changes

2022-01-22 15:40 UTC, dkrutskikh requested changes

2022-01-22 15:40 UTC, dkrutskikh commented on lib/src/core/services/exceptions/server/server_error_mapper.dart
> +  static const int _unauthorized = 401;
@beersheba давай отсортируем в порядке возрастания номера ошибки

2022-01-22 15:40 UTC, dkrutskikh commented on lib/src/core/services/exceptions/server/server_error_mapper.dart
>    static Exception fromDioError(DioError error) {
@beersheba давай напишем тесты, будем проверять типы генерируемых исключений

2022-01-22 15:40 UTC, dkrutskikh commented on lib/src/core/services/network/dio/error_code_interceptor.dart
> +      handler.next(err);
@beersheba как я понимаю документацию, нам всегда надо передавать управление следующим хендлерам

2022-01-23 19:52 UTC, beersheba commented on lib/src/core/services/network/dio/error_code_interceptor.dart
> +      handler.next(err);
я понял, что нам надо обработать 400 и 401, в остальных случаях передаем следующему интерцептору

> Необходимо написать Interceptors, которые делают следующее:
>  Обрабатывает HTTP код и приводит его к Exception либо передает управление следующему Interceptor.
>  Если HTTP код 400 - парсит тело ошибки и по внутреннему коду бросает новый кастомный Exception.
>  Если пришла 401 - оставить TODO с сообщение о необходимости попытки перезапросить токен, и вывести сообщение в консоль.

2022-01-23 19:53 UTC, beersheba commented on lib/src/core/services/exceptions/server/server_error_mapper.dart
>    static Exception fromDioError(DioError error) {
@dkrutskikh что ты имеешь ввиду? тесты на типы 400-404 уже есть

2022-01-23 20:00 UTC, beersheba commented on lib/src/core/services/exceptions/server/server_error_mapper.dart
> +  static const int _unauthorized = 401;
@dkrutskikh ok

2022-01-25 12:36 UTC, dkrutskikh approved these changes

2022-01-25 12:36 UTC, merged