feat: base button
boostgrade/wtgt_gamma pull request #15
Opened 2022-01-24 17:32 UTC by Veselchak-U

# Ссылка на задачу
Задача #3

# Что было сделано

Создан виджет WtgtButton добавляющий в стандартный TextButton состояние "loading", управляемое с помощью конструктора.
Индикатор загрузки вынесен в отдельный виджет WtgtCircularProgressIndicator для возможного переиспользования.

# Как проверить работу?

Виджет-тест: \test\uikit\wtgt_button_test.dart

# Чек-лист

- [x] Функциональность протестирована и работает корректно
- [x] Если в задаче есть верстка - прикреплен скриншот или запись экрана

https://user-images.githubusercontent.com/57040655/150834324-1bd26e56-835f-44cd-aa65-525f138ea692.mp4

2022-01-25 10:56 UTC, dkrutskikh commented
@Veselchak-U надо внести запись в changelog

2022-01-25 10:56 UTC, dkrutskikh requested changes

2022-01-25 10:56 UTC, dkrutskikh commented on lib/src/ui/uikit/wtgt_circular_progress_indicator.dart
> +        strokeWidth: 3,
@Veselchak-U давай жирность привяжем к размеру индикатора

2022-01-25 12:34 UTC, beersheba commented on lib/src/features/app/ui/app.dart
> +                    side: BorderSide(color: Color(0xFF184E9E)),
можно вынести цвет в const, он несколько раз встречается

2022-01-25 13:56 UTC, Veselchak-U commented on lib/src/features/app/ui/app.dart
> +                    side: BorderSide(color: Color(0xFF184E9E)),
Это всё уйдёт в AppTheme. Здесь я вставил кусок для проверки отображения, пока AppTheme не готова.

2022-01-25 14:11 UTC, Veselchak-U commented on lib/src/ui/uikit/wtgt_circular_progress_indicator.dart
> +        strokeWidth: 3,
Привязал.

2022-01-25 15:01 UTC, dkrutskikh commented on lib/src/ui/uikit/wtgt_button.dart
> +        onPressed: loading ? null : onPressed,
@Veselchak-U в момент загрузки кнопка будет в отключенном состоянии. может стоит написать так

```dart
onPressed: loading ? () {} : onPressed,
```

2022-01-25 15:05 UTC, dkrutskikh requested changes

2022-01-25 15:05 UTC, dkrutskikh commented on test/uikit/wtgt_button_test.dart
> +          const label = 'hello!';
@Veselchak-U не очень понятно чем не угодило прошлое название константы?

2022-01-25 15:05 UTC, dkrutskikh commented on test/uikit/wtgt_button_test.dart
> +          var button = const WtgtButton(
@Veselchak-U давайте сразу писать в константу, не вижу смысла создавать константный объект и записывать в переменную

2022-01-25 15:05 UTC, dkrutskikh commented on test/uikit/wtgt_button_test.dart
> +          button = const WtgtButton(
@Veselchak-U второй вариант кнопки лучше вынести во второй тест, так получится что каждый кейс мы тестируем максимально изолированно

2022-01-27 19:11 UTC, Veselchak-U commented on test/uikit/wtgt_button_test.dart
> +          const label = 'hello!';
Вернул.

2022-01-27 19:12 UTC, Veselchak-U commented on test/uikit/wtgt_button_test.dart
> +          var button = const WtgtButton(
Переделал тесты на golden.

2022-01-27 19:12 UTC, Veselchak-U commented on test/uikit/wtgt_button_test.dart
> +          button = const WtgtButton(
Переделал тесты на golden.

2022-01-27 19:13 UTC, Veselchak-U commented on lib/src/ui/uikit/wtgt_button.dart
> +        onPressed: loading ? null : onPressed,
Сделал, но теперь линтер ругается на "info: Block is empty. Empty blocks are often indicators of missing code. (no-empty-block at [where_to_go_today] lib\src\ui\uikit\wtgt_button.dart:23)"

2022-01-27 19:19 UTC, Veselchak-U commented on lib/src/ui/uikit/wtgt_button.dart
> +        onPressed: loading ? null : onPressed,
Добавил // ignore: no-empty-block

2022-01-27 22:46 UTC, NeoZ3p approved these changes

2022-01-28 03:26 UTC, dkrutskikh approved these changes

2022-01-28 03:26 UTC, merged