feat: token storage
boostgrade/wtgt_gamma pull request #32
Opened 2022-01-28 20:48 UTC by beersheba

# Ссылка на задачу
Задача #27 

# Что было сделано

Подключен и настроен модуль Hive, выполняющий локальное хранение данных. 
Реализован класс TokenStorage, инкапсулирующий работу с хранилищем.

# Как проверить работу?

Функционал класса TokenStorage описан тестами
test/storage/token_storage_test.dart

# Чек-лист

- [ ] Функциональность протестирована и работает корректно

2022-01-28 20:54 UTC, NeoZ3p approved these changes

2022-01-29 00:17 UTC, dkrutskikh requested changes

2022-01-29 00:17 UTC, dkrutskikh commented on lib/src/features/auth/services/storage/token_storage.dart
> +const String keyToken = 'auth_token';
@beersheba почему эти константы публичны?

2022-01-29 00:17 UTC, dkrutskikh commented on lib/src/features/auth/services/storage/token_storage.dart
> +  Future<void> openBox() async {
@beersheba мы планируем вызывать этот метод из нашего бизнес кода? И как часто мы планируем его вызывать вообще?

2022-01-29 09:49 UTC, beersheba commented on lib/src/features/auth/services/storage/token_storage.dart
> +const String keyToken = 'auth_token';
@dkrutskikh поправил

2022-01-29 09:50 UTC, beersheba commented on lib/src/features/auth/services/storage/token_storage.dart
> +  Future<void> openBox() async {
@dkrutskikh на этапе инита и в тесте. добавил скорее ради теста.

2022-01-29 09:51 UTC, beersheba commented on lib/src/features/auth/services/storage/token_storage.dart
> +  Future<void> openBox() async {
@dkrutskikh так лучше?

2022-01-29 09:55 UTC, dkrutskikh requested changes

2022-01-29 09:55 UTC, dkrutskikh commented on lib/src/features/auth/services/storage/token_storage.dart
> +    await openBox(_tokenBox);
@beersheba можно не ожидать тут фьючера а вернуть его - пусть дожидается тот кому нужно дождаться полной инициализации

2022-01-29 09:55 UTC, dkrutskikh commented on lib/src/features/auth/services/storage/token_storage.dart
> +  Future<void> openBox(String boxName) async {
@beersheba проблема в том что это публичный метод, а значит его может вызвать кто угодно. Если он нужен тесту - добавь аннотацию `@visibleForTesting`

2022-01-29 11:29 UTC, beersheba commented on lib/src/features/auth/services/storage/token_storage.dart
> +  Future<void> openBox(String boxName) async {
@dkrutskikh добавил

2022-01-29 11:30 UTC, beersheba commented on lib/src/features/auth/services/storage/token_storage.dart
> +    await openBox(_tokenBox);
@dkrutskikh ok

2022-01-29 16:32 UTC, dkrutskikh approved these changes

2022-01-29 16:32 UTC, merged