feat: sign_in_screen
boostgrade/wtgt_gamma pull request #33
Opened 2022-01-28 21:50 UTC by Veselchak-U

# Ссылка на задачу
Задача #25 

# Что было сделано

Добавлен экран ввода номера телефона для авторизации. 
Для обработки форматирования номера телефона по маске используется внешний пакет mask_text_input_formatter. 
Для кнопок логина через соцсети добавлен вспомогательный виджет SotialLoginButton.
Для реализации корректного нижнего отступа у этих кнопок для разных размеров экрана, используется динамический расчёт отступа в зависимости от высоты экрана.
Изображения из макета подключены в виде PNG, т.к. SVG из Figma сохраняется в нечитаемом для Flutter виде.

# Как проверить работу?

В класс MainScreenRoute подставить запуск экрана при старте приложения:
builder: (context) => const SignInScreen(),

# Чек-лист

- [x] Функциональность протестирована и работает корректно
- [x] Если в задаче есть верстка - прикреплен скриншот или запись экрана

![Screenshot_1643405634](https://user-images.githubusercontent.com/57040655/151626367-18cf8f69-21b7-4978-ae80-f15f8d625183.png)

2022-01-29 04:53 UTC, dkrutskikh requested changes
@Veselchak-U иконки лучше иметь в svg

2022-01-29 08:54 UTC, NeoZ3p commented on lib/src/features/auth/sign_in/sign_in_screen.dart
> +          child: Padding(
У SingleChildScrollView есть свойство padding, можно убрать виджет Padding

2022-01-29 08:55 UTC, NeoZ3p commented on lib/src/features/auth/sign_in/sign_in_screen.dart
> +                    labelText: 'Номер телефона',
У нас ведь есть локализация, зачем хардкодить текст?

2022-01-29 08:55 UTC, NeoZ3p commented on lib/src/features/auth/sign_in/sign_in_screen.dart
> +                  label: 'Отправить',
Опять же локализация

2022-01-29 08:57 UTC, NeoZ3p commented on lib/src/features/auth/sign_in/sotial_login_button.dart
> +    this.onPressed,
Для большей читабельности я бы расположил параметры в следующем порядке: required > optional

2022-01-29 08:58 UTC, NeoZ3p requested changes
В остальном всё ок :)

2022-01-29 13:24 UTC, Veselchak-U commented
> @Veselchak-U иконки лучше иметь в svg

Сконвертировал в SVG.

2022-01-29 13:27 UTC, Veselchak-U commented on lib/src/features/auth/sign_in/sign_in_screen.dart
> +          child: Padding(
Исправил.

2022-01-29 13:27 UTC, Veselchak-U commented on lib/src/features/auth/sign_in/sign_in_screen.dart
> +                    labelText: 'Номер телефона',
Добавил локализацию.

2022-01-29 13:27 UTC, Veselchak-U commented on lib/src/features/auth/sign_in/sign_in_screen.dart
> +                  label: 'Отправить',
Добавил локализацию.

2022-01-29 13:32 UTC, Veselchak-U commented on lib/src/features/auth/sign_in/sotial_login_button.dart
> +    this.onPressed,
Key везде идёт первым именованным параметром. В некоторых линтёрах даже есть правило на этот счёт.

2022-01-29 21:38 UTC, NeoZ3p commented on lib/src/localization/l10n.dart
> +  AppLocalizations get l10n => AppLocalizations.of(this)!;
Не думаю, что "!" хорошая идея, потому что, в случае удаления какого-либо поля в .arb файле локализации, будет ошибка

2022-01-29 21:42 UTC, NeoZ3p requested changes
👌

2022-01-30 09:48 UTC, beersheba approved these changes

2022-01-30 09:48 UTC, beersheba commented on lib/src/features/auth/sign_in/sign_in_screen.dart
> +            mainAxisSize: MainAxisSize.min,
@Veselchak-U зачем здесь нужно выставлять mainAxisSize?

2022-01-30 09:54 UTC, Veselchak-U commented on lib/src/localization/l10n.dart
> +  AppLocalizations get l10n => AppLocalizations.of(this)!;
Здесь в контексте ищется не само текстовое поле, а класс, в котором это поле находится. И этот класс в контексте по идее должен быть всегда, иначе вся локализация не будет работать.
Если же из .arb удалить используемое текстовое поле и перегенерить классы локализации - то текущий код просто не скомпилируется.

2022-01-30 10:04 UTC, Veselchak-U commented on CHANGELOG.md
> +* feat: sign_in_screen
Исправил.

2022-01-30 10:05 UTC, Veselchak-U commented on lib/src/features/auth/sign_in/sign_in_screen.dart
> +            mainAxisSize: MainAxisSize.min,
Да, все элементы имеют фиксированную высоту, поэтому здесь это лишнее - убрал.

2022-01-31 15:49 UTC, NeoZ3p approved these changes

2022-01-31 16:11 UTC, loopnyapy approved these changes

2022-01-31 17:56 UTC, merged