feat: register_screen
boostgrade/wtgt_gamma pull request #34
Opened 2022-01-29 18:05 UTC by NeoZ3p

# Ссылка на задачу
Задача #26 

# Что было сделано

- Сверстана страница по макету
- Добавлены валидаторы для инпутов
- Использован файл keyboard_listener, позволяющий прятать кнопку внизу экрана, когда открывается клавиатура

# Как проверить работу?

- Поменять в классе lib>src>features>main>main_screen_route.dart виджет вместо Provider на RegisterScreen

# Чек-лист

- [ ] Функциональность протестирована и работает корректно

![image](https://user-images.githubusercontent.com/72041941/151672112-67370caf-ac21-4780-9e42-80f12f0c16cb.png)

2022-01-29 20:47 UTC, Veselchak-U commented on lib/src/features/auth/register/register_screen.dart
> +            autovalidateMode: AutovalidateMode.onUserInteraction,
Автовалидация всей формы по любому нажатию, не очень дружественное для пользователя поведение. Он же ещё не дошёл до следующего поля - а оно уже невалидное.
Лучше оставить autovalidateMode: AutovalidateMode.onUserInteraction для каждого поля отдельно.

2022-01-29 20:48 UTC, Veselchak-U commented on lib/src/features/auth/register/register_screen.dart
> +                  validator: _fullNameValidator,
Лучше сразу не давать возможности вводить некорректные символы путём добавления в TextFormField фильтра на ввод:
inputFormatters: [
  FilteringTextInputFormatter.allow(RegExp(r'[А-Яа-яёЁ\-]')),
],
А проверки введённого значения на длину, первый символ не тире и т.д. проводить уже в validator.

2022-01-29 20:49 UTC, Veselchak-U commented on lib/src/features/auth/register/register_screen.dart
> +                  ),
Для улучшения пользовательского опыта в TextFormField есть поле:
keyboardType: TextInputType.name/emailAddress/datetime,

2022-01-29 20:49 UTC, Veselchak-U commented on lib/src/features/auth/register/register_screen.dart
> +                  decoration: InputDecoration(
Также для улучшения пользовательского опыта в TextFormField есть поле, которое по нажатию "ввод" переходит на следующее поле в форме:
textInputAction: TextInputAction.next,

2022-01-29 20:50 UTC, Veselchak-U commented on lib/src/features/auth/register/register_screen.dart
> +                  ),
Для красоты, чтобы при ошибке валидации расстояние между полями не прыгало, можно добавить в
decoration: InputDecoration(                    
  helperText: '',
),
Но тогда и расстояние между полями нужно уменьшать на высоту шрифта.

2022-01-29 20:51 UTC, Veselchak-U commented on lib/src/features/auth/register/register_screen.dart
> +    if (_formKey.currentState!.validate()) {
Сюда нужно добавить проверку состояния чекбокса - если не нажат, то в целом форма невалидна.

2022-01-29 20:51 UTC, Veselchak-U commented on lib/src/features/auth/register/register_screen.dart
> +                  onChanged: _onChangedCheckbox,
Если форма и чекбокс невалидны, то кнопка должна быть задизейблена.

2022-01-29 20:52 UTC, Veselchak-U commented on lib/src/features/auth/register/register_screen.dart
> +      floatingActionButton: _isKeyboardVisible
Это конечно интересно смотрится, но работает не всегда корректно. Например, на таком экране чекбокс вообще не виден за кнопкой.
Плюс, мы лишаем пользователя возможности нажать кнопку при открытой клавиатуре, даже если вся форма валидна.
![Screenshot_1643488291](https://user-images.githubusercontent.com/57040655/151677200-d0b35553-2cd8-40ff-888e-0bbe416ffa18.png)

2022-01-29 20:54 UTC, NeoZ3p commented on lib/src/features/auth/register/register_screen.dart
> +      floatingActionButton: _isKeyboardVisible
Этот способ предложил @dkrutskikh, потому что в другом случае кнопка будет вылазить наверх и закрывать контент

2022-01-29 20:55 UTC, NeoZ3p commented on lib/src/features/auth/register/register_screen.dart
> +      floatingActionButton: _isKeyboardVisible
Разве скролл не работает? страница обернута в SingleChildScrollView

2022-01-29 21:20 UTC, NeoZ3p commented on lib/src/features/auth/register/register_screen.dart
> +                  ),
Я думаю не стоит ломать тему)

2022-01-29 21:22 UTC, Veselchak-U commented on lib/src/features/auth/register/register_screen.dart
> +      floatingActionButton: _isKeyboardVisible
> Разве скролл не работает? страница обернута в SingleChildScrollView

Скролл работает, но FloatActionButton накладывается поверх контента.

2022-01-30 04:10 UTC, dkrutskikh commented on lib/src/features/auth/register/register_screen.dart
> +                  ),
@NeoZ3p лучше поправить то что написал @Veselchak-U

2022-01-30 04:13 UTC, dkrutskikh commented on lib/src/features/auth/register/register_screen.dart
> +      floatingActionButton: _isKeyboardVisible
@Veselchak-U какие будут твои предложения для телефонов с маленьким экраном?

2022-01-30 04:14 UTC, dkrutskikh commented
@NeoZ3p подлей мастер и changelog запись добавь в нужный блок

2022-01-30 09:40 UTC, Veselchak-U commented on lib/src/features/auth/register/register_screen.dart
> +      floatingActionButton: _isKeyboardVisible
У меня реализован динамический отступ, в зависимости от видимой области экрана:
lib/src/features/auth/sign_in/sign_in_screen.dart

2022-01-30 09:44 UTC, Veselchak-U commented on lib/src/features/auth/register/register_screen.dart
> +                  keyboardType: TextInputType.datetime,
Надо на это поле тоже навесить валидатор или задать маску ввода.
Для ввода в поле по маске обрати внимание на пакет "mask_text_input_formatter".
В экране ввода телефона я как раз его использовал: lib/src/features/auth/sign_in/sign_in_screen.dart

2022-01-30 10:46 UTC, beersheba requested changes

2022-01-30 10:46 UTC, beersheba commented on lib/src/features/auth/register/register_screen.dart
> +                    AppLocalizations.of(context)!.acceptUserAgreement,
это не должно быть кликабельно? обычно сюда добавляют гиперлинк с соглашением

2022-01-30 10:46 UTC, beersheba commented on lib/src/features/auth/register/register_screen.dart
> +              child: TextButton(
тут стоит использовать WtgtButton, можно смержить из мастера

2022-01-30 10:46 UTC, beersheba commented on lib/src/features/auth/register/register_screen.dart
> +      floatingActionButton: _isKeyboardVisible
почему бы просто не открывать клавиатуру поверх? кнопка будет всегда находиться внизу формы. клавиатуру можно закрыть по кнопке back или по нажатию на любое место экрана. если все поля заполнены, можно также вызвать _registerBtnClicked через textInputAction

2022-01-30 11:03 UTC, beersheba commented on lib/src/features/auth/register/register_screen.dart
> +      floatingActionButton: _isKeyboardVisible
[в соседней задаче](https://github.com/boostgrade/wtgt_gamma/issues/24) есть указание на этот счет:
> Если при поднятой клавиатуре кнопка перекрывает поле ввода, поле ввода должно подскралливаться.

2022-01-30 18:24 UTC, Veselchak-U commented on lib/src/features/auth/register/register_screen.dart
> +                    hintText: '##/##/####',
Здесь для пользователю нужно показать что-то более осмысленное: "дд/мм/гггг" и "dd/mm/yyyy".
Также нужно повесить валидатор введённой даты, что-то вроде:

  String? _birthdayValidator(String? value) {
    if (!_maskFormatter.isFill()) return null;
    try {
      final birthday = DateFormat('dd/MM/yyyy').parseStrict(value ?? '');
      final now = DateTime.now();
      final hundredYearsAgo = now.subtract(const Duration(days: 365 * 100));
      if (birthday.isAfter(now) || birthday.isBefore(hundredYearsAgo)) {
        return AppLocalizations.of(context)?.valueIsIncorrect;
      }
      return null;
    } on FormatException {
      return AppLocalizations.of(context)?.valueIsIncorrect;
    }
  }

2022-01-31 16:08 UTC, loopnyapy approved these changes

2022-01-31 16:34 UTC, Veselchak-U approved these changes

2022-02-01 15:41 UTC, beersheba approved these changes

2022-02-02 15:23 UTC, merged