Code screen
boostgrade/wtgt_gamma pull request #35
Opened 2022-01-29 18:11 UTC by NeoZ3p

# Ссылка на задачу
Задача #24 

# Что было сделано

- Сверстана страница по макету
- Добавлено ограничение на количество вводимых цифр в инпут
- Использован файл keyboard_listener, позволяющий прятать кнопку внизу экрана, когда открывается клавиатура

# Как проверить работу?

- Поменять в классе lib>src>features>main>main_screen_route.dart виджет вместо Provider на CodeScreen

# Чек-лист

- [ ] Функциональность протестирована и работает корректно

![image](https://user-images.githubusercontent.com/72041941/151672387-b9fa2b9f-92e0-4826-b883-e60e97401587.png)

2022-01-29 21:16 UTC, Veselchak-U commented on lib/src/features/auth/code/code_screen.dart
> +      floatingActionButton: _isKeyboardVisible
Как я писал здесь: https://github.com/boostgrade/wtgt_gamma/pull/34#discussion_r795092298
на мой взгляд, это спорное решение.
Мне кажется лучше это делать через динамическое вычисление отступа, как это сделано у меня:
lib/src/features/auth/sign_in/sign_in_screen.dart

2022-01-30 10:59 UTC, beersheba requested changes

2022-01-30 10:59 UTC, beersheba commented on lib/src/features/auth/code/code_screen.dart
> +      floatingActionButton: _isKeyboardVisible
согласен, добавляет странную анимацию для уезжающей кнопки при открывании клавиатуры на андроиде

2022-01-30 10:59 UTC, beersheba commented on lib/src/features/auth/code/code_screen.dart
> +              child: TextButton(
тут должна быть WtgtButton

2022-01-30 10:59 UTC, beersheba commented on lib/src/features/auth/code/code_screen.dart
> +              Image.asset('assets/images/3.0x/wtgt_logo.png'),
лого не по центру

2022-01-30 11:04 UTC, beersheba commented on lib/src/features/auth/code/code_screen.dart
> +      floatingActionButton: _isKeyboardVisible
> Если при поднятой клавиатуре кнопка перекрывает поле ввода, поле ввода должно подскралливаться.

2022-01-31 16:39 UTC, Veselchak-U approved these changes

2022-01-31 16:40 UTC, Veselchak-U commented
Аппрув, но в будущем надо будет добавить деактивацию кнопки, если поле незаполненно.

2022-02-01 15:41 UTC, beersheba approved these changes

2022-02-02 18:21 UTC, loopnyapy approved these changes

2022-02-06 17:47 UTC, dkrutskikh approved these changes

2022-02-06 17:48 UTC, dkrutskikh approved these changes

2022-02-06 17:48 UTC, merged