feat: google sign in
boostgrade/wtgt_gamma pull request #49
Opened 2022-02-15 15:33 UTC by loopnyapy

# Ссылка на задачу
Задача #29 

# Что было сделано

- Создано тестовое приложение в FireBase
- Проведена настройка на стороне ios
- Проведена настройка на стороне android
- Создана и подключена ViewModel на страницу SignInScreen
- Создан SignInRoute
- Реализован сервис GoogleAuth для работы с [google_sign_in](https://pub.dev/packages/google_sign_in)
- Добавлена ошибка в server_error_exception.dart и использована в SnackBarErrorScenarios
- Подключен CanThrowExceptionBlocMixin в AuthBloc
- Добавлены зависимости GoogleAuth и AuthBloc в AppDependencies
- Добавлены параметры error и stackTrace для AuthStateError

# Как проверить работу?

- Запустить приложение и нажать на кнопку с иконкой Google

# Чек-лист

- [ ] Функциональность протестирована и работает корректно

2022-02-19 15:54 UTC, Veselchak-U approved these changes

2022-02-20 21:06 UTC, beersheba approved these changes

2022-02-22 00:02 UTC, NeoZ3p approved these changes

2022-02-22 16:51 UTC, dkrutskikh requested changes

2022-02-22 16:51 UTC, dkrutskikh commented on lib/src/core/ui/errors_handling/scenario_error_handler/scenarios/snackbar_error_scenarios.dart
> +// / Реализация сценария, при котором при каждой ошибке всплывает снекбар
зачем тут добавил пробел?

2022-02-22 16:51 UTC, dkrutskikh commented on lib/src/features/auth/services/auth_bloc.dart
> +        emit(AuthState.error(Exception(), s));
@loopnyapy верни оригинальный

2022-02-23 14:46 UTC, dkrutskikh approved these changes

2022-02-23 14:48 UTC, merged