Facebook logic
boostgrade/wtgt_gamma pull request #52
Opened 2022-02-21 23:21 UTC by NeoZ3p

# Ссылка на задачу
Задача #28

# Что было сделано

- Была проведена настройка iOS и Android.
- Сделан сервис для работы с плагином.
- Реализован функционал по нажатию на кнопку.

# Как проверить работу?

Нажать на кнопку с иконкой Facebook

# Чек-лист

- [ ] Функциональность протестирована и работает корректно

2022-02-22 06:01 UTC, Veselchak-U approved these changes

2022-03-19 17:38 UTC, beersheba commented on lib/src/features/auth/services/facebook/facebook_auth_service.dart
> +    return result.status == LoginStatus.success && result.accessToken != null
@NeoZ3p В случае ошибки пользователю должно показываться сообщение в виде снека

2022-03-19 17:46 UTC, beersheba requested changes
Конфигурация под андроид не завершена

2022-03-19 17:46 UTC, beersheba commented on android/app/src/main/res/values/strings.xml
> +   <string name="fb_login_protocol_scheme">fb321585666565525</string>
@NeoZ3p тут вроде еще токен нужен
https://facebook.meedu.app/docs/4.x.x/android

2022-03-19 17:46 UTC, beersheba commented on lib/src/features/auth/services/facebook/facebook_auth_service.dart
> +    return result.status == LoginStatus.success && result.accessToken != null
В случае ошибки пользователю должно показываться сообщение в виде снека

2022-03-21 19:24 UTC, NeoZ3p commented on android/app/src/main/res/values/strings.xml
> +   <string name="fb_login_protocol_scheme">fb321585666565525</string>
✅

2022-03-23 20:31 UTC, beersheba commented on lib/src/features/auth/services/facebook/facebook_auth_service.dart
> +    return result.status == LoginStatus.success && result.accessToken != null
посмотри как это сделано для вк и google. если вернуться на главный экран без токена, выскочит ошибка

2022-03-29 03:40 UTC, dkrutskikh approved these changes

2022-03-29 03:40 UTC, merged