feat: registration logic
boostgrade/wtgt_gamma pull request #53
Opened 2022-02-22 07:48 UTC by NeoZ3p

# Ссылка на задачу
Задача #22

# Что было сделано
- Создана RegisterVm
- Сделан роут RegisterRoute
- VM подключена к экрану RegisterPage

# Как проверить работу?
- Запустить приложение, ввести значения в поля и нажать на кнопку "Зарегистрироваться"

# Чек-лист
- [ ] Функциональность протестирована и работает корректно

2022-02-24 06:18 UTC, Veselchak-U commented on test/auth/register_screen/register_screen_test.dart
> +  final appDependencies = AppDependencies();
Вот это лучше замокать, чтобы тест не ходил в реальные репозитории.
Образец можно посмотреть в ветке "feat/code_vm" файл test/auth/code_screen)/code_screen_test.dart

2022-03-01 10:40 UTC, NeoZ3p commented on test/auth/register_screen/register_screen_test.dart
> +  final appDependencies = AppDependencies();
Сделал

2022-03-18 20:15 UTC, Veselchak-U commented on lib/src/features/auth/register/register_screen_vm.dart
> +  TextEditingController nameController = TextEditingController();
Контроллеры созданы, а dispose() нет.

2022-03-18 20:28 UTC, Veselchak-U commented on lib/src/features/auth/register/register_screen.dart
> +                    loading: vm.vmState == RegisterVmState.loading,
Это условие просится на вынос в VM.

2022-03-18 20:37 UTC, Veselchak-U commented on lib/src/features/auth/register/register_screen_vm.dart
> +  TextEditingController surnameController = TextEditingController();
@observable не нужен для переменных, которые не меняются из VM и на изменение которых не должен реагировать UI. Т.е. в данном случае мы один раз инициализируем переменную ссылкой на объект и больше эта переменная не меняется. Меняется содержимое объекта внутри.
Также не нужно делать @observable валидаторы.

2022-03-18 20:46 UTC, Veselchak-U commented on lib/src/features/auth/register/register_screen_vm.dart
> +  String? emailValidator(String? value) {
@action нужен для методов, которые изменяют @observable-переменные.
Внутри валидатора никакие внешние переменные не изменяются.

2022-03-18 20:47 UTC, Veselchak-U commented on lib/src/features/auth/register/register_screen_vm.dart
> +  void registerBtnClicked() {
Тут тоже @action излишний. Внутри метода никакие внешние переменные не изменяются.

2022-03-18 21:02 UTC, Veselchak-U commented on lib/src/features/auth/register/register_screen_vm.dart
> +    if (maskFormatter.isFill()) return null;
Сейчас позволяет ввести будущее время в дату рождения.

2022-03-19 19:53 UTC, beersheba requested changes

2022-03-19 19:53 UTC, beersheba commented on lib/src/features/auth/register/register_screen_vm.dart
> +      }
@NeoZ3p это надо вынести в отдельный метод и выполнять при изменении каждого поля, а не только чекбокса

2022-03-20 09:47 UTC, NeoZ3p commented on lib/src/features/auth/register/register_screen_vm.dart
> +  String? emailValidator(String? value) {
✅

2022-03-20 09:47 UTC, NeoZ3p commented on lib/src/features/auth/register/register_screen_vm.dart
> +  void registerBtnClicked() {
✅

2022-03-20 09:47 UTC, NeoZ3p commented on lib/src/features/auth/register/register_screen_vm.dart
> +  TextEditingController surnameController = TextEditingController();
✅

2022-03-20 16:43 UTC, NeoZ3p commented on lib/src/features/auth/register/register_screen_vm.dart
> +  TextEditingController nameController = TextEditingController();
✅

2022-03-23 19:13 UTC, beersheba approved these changes

2022-03-24 09:25 UTC, loopnyapy approved these changes

2022-03-24 10:16 UTC, mechartcap approved these changes

2022-03-24 10:21 UTC, Veselchak-U approved these changes

2022-03-29 03:41 UTC, dkrutskikh approved these changes

2022-03-29 03:41 UTC, merged