Feat/main screen pr
boostgrade/wtgt_gamma pull request #62
Opened 2022-03-27 17:38 UTC by Veselchak-U

# Ссылка на задачу
Задача #54 

# Что было сделано
1) Реализован экран с табами: \lib\src\features\main\main_screen.dart. 
TabController из вёрстки в VM не выносится, т.к. он требует SingleTickerProviderStateMixin, который в VM недоступен.
VM для данного экрана фактически не задействована, но оставлена для возможного дальнейшего расширения функциональности.
Все зависимости для экранов, используемых в качестве табов, прописываются в MainRoute. Т.к. эти экраны не не имеют собственных route и будут вызываться только через main_screen.
Для возможности открытия main_screen на определённом табе, в MainRoute добавлен параметр initialScreen.

2) Реализован экран первого таба: \lib\src\features\main\places\ui\places_screen.dart.
Чтобы экран не пересоздавался при переключении на другие табы, используется AutomaticKeepAliveClientMixin.
Реализована заготовка bloc: \lib\src\features\main\places\service\places_bloc.dart
Реализована заготовка repository: \lib\src\features\main\places\service\repository\places_repository.dart
Данные пока отдаются замоканные.
Добавлена модель заведения: \lib\src\core\domain\place.dart

3) Реализованы заголовки экранов для остальных табов:
- \lib\src\features\main\my_card\my_card_screen.dart
- \lib\src\features\main\profile\profile_screen.dart
И экрана с деталями заведения:
- \lib\src\features\place_detail\place_detail_screen.dart

# Как проверить работу?
Перейти в ветку feat/main_screen_pr, запустить приложение.

# Чек-лист
- [x] Функциональность протестирована и работает корректно
- [x] Если в задаче есть верстка - прикреплен скриншот или запись экрана
![Screenshot_1648402690](https://user-images.githubusercontent.com/57040655/160293583-50649722-6381-4bca-9807-acd3c52d07b9.png)

2022-03-27 20:48 UTC, NeoZ3p approved these changes

2022-04-02 14:54 UTC, beersheba approved these changes

2022-04-02 14:54 UTC, beersheba commented on lib/src/localization/app_en.arb
> +  "restaurantName": "The name of the restaurant?",
думаю лучше вместо ресторана использовать `place`

2022-04-02 20:51 UTC, dkrutskikh requested changes

2022-04-02 20:51 UTC, dkrutskikh commented on assets/images/place/icon_share.svg
> +<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
@Veselchak-U почему эта иконка в векторе а прошлая в растре?

2022-04-02 20:51 UTC, dkrutskikh commented on pubspec.yaml
> +  mockito: ^5.1.0
@Veselchak-U зачем нам этот пакет?

2022-04-02 20:51 UTC, dkrutskikh commented on lib/src/core/domain/place.dart
> +  final int? distance;
это лучше сделать в рамках другой задачи

2022-04-03 15:00 UTC, Veselchak-U commented on lib/src/core/domain/place.dart
> +  final int? distance;
Не возражаю сделать это в рамках другой задачи.

2022-04-03 15:07 UTC, Veselchak-U commented on lib/src/localization/app_en.arb
> +  "restaurantName": "The name of the restaurant?",
Исправил.

2022-04-03 15:15 UTC, Veselchak-U commented on assets/images/place/icon_share.svg
> +<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
Предпочитаю иконки в SVG, однако предыдущая иконка "\assets\images\place\icon_cocktail.png" в формате SVG занимает в 15 раз больше места, чем она же в формате PNG. Поэтому оставил её в PNG.

2022-04-03 15:20 UTC, Veselchak-U commented on pubspec.yaml
> +  mockito: ^5.1.0
Подлилось во время какого-то мёржа, убрал.

2022-04-03 23:16 UTC, NeoZ3p approved these changes

2022-04-04 08:59 UTC, beersheba approved these changes

2022-04-04 15:38 UTC, merged