Feat/profile screen
boostgrade/wtgt_gamma pull request #63
Opened 2022-03-27 20:05 UTC by beersheba

# Ссылка на задачу
Задача #56 

# Что было сделано

Выполнена верстка экрана Профиль.

# Как проверить работу?

Запустить приложение, переключиться на вкладку Профиль

# Чек-лист

- [ ] Функциональность протестирована и работает корректно
- [ ] Если в задаче есть верстка - прикреплен скриншот или запись экрана

<img src=https://user-images.githubusercontent.com/13087114/160298634-a13ebab4-dc72-4e9f-8529-6d57f93e643a.png width="300" />

2022-03-27 20:50 UTC, NeoZ3p commented on lib/src/features/profile/ui/profile/favorite_place.dart
> +class _FavoritePlaceState extends State<FavoritePlace> {
Не совсем понял зачем тут стейтфул виджет, если используется только билд метод

2022-03-27 20:53 UTC, NeoZ3p commented on lib/src/features/profile/ui/profile/favorite_place.dart
> +                        ? '${widget.place.distance} м'
Не хватает локализации, а то на английском странно будет выглядеть с "м"

2022-03-27 20:53 UTC, NeoZ3p commented on lib/src/features/profile/ui/profile/profile_screen.dart
> +class _ProfileScreenState extends State<ProfileScreen> {
Опять же стейтфул виджет

2022-03-27 20:54 UTC, NeoZ3p commented on lib/src/features/profile/ui/profile/profile_screen.dart
> +                            onTap: () {
Я бы вынес эту обработку нажатия на кнопку в отдельную функцию

2022-03-27 20:54 UTC, NeoZ3p commented on lib/src/features/profile/ui/profile/profile_screen.dart
> +                              onPressed: () {
Тоже самое с отдельной функцией

2022-03-27 20:54 UTC, NeoZ3p commented on lib/src/features/profile/ui/profile/profile_screen.dart
> +                  onPressed: () {
И тут

2022-03-27 20:54 UTC, NeoZ3p commented on lib/src/features/profile/ui/profile/profile_screen.dart
> +              onPressed: () {
И еще раз тут)

2022-03-27 20:59 UTC, NeoZ3p requested changes
👌

2022-03-28 19:22 UTC, Veselchak-U commented on lib/src/features/profile/ui/profile/profile_screen.dart
> +                        backgroundImage: NetworkImage(widget.user.photoUrl),
Рекомендую в качестве ImageProvider-а использовать библиотеку cached_network_image - много опций + скачанные изображения кэшируются.

2022-03-28 20:14 UTC, Veselchak-U commented on lib/src/features/profile/ui/profile/profile_screen.dart
> +                            onTap: () {
Вообще все обработчики нажатий просятся в VM.

2022-03-28 20:20 UTC, Veselchak-U commented on lib/src/features/profile/ui/profile/profile_screen.dart
> +                  child: Row(
Мудрёная получилась вёрстка. Для интереса глянь мой вариант:
https://github.com/boostgrade/wtgt_gamma/blob/experiment/profile_screen/lib/src/features/profile/ui/profile/profile_screen.dart

2022-03-29 16:12 UTC, beersheba commented on lib/src/features/profile/ui/profile/profile_screen.dart
> +class _ProfileScreenState extends State<ProfileScreen> {
Согласно требованиям, экран должен быть реализован как StatefulWidget

2022-03-29 20:29 UTC, beersheba commented on lib/src/features/profile/ui/profile/favorite_place.dart
> +                        ? '${widget.place.distance} м'
Добавил

2022-03-29 20:30 UTC, beersheba commented on lib/src/features/profile/ui/profile/favorite_place.dart
> +  const FavoritePlace(this.place, {Key? key}) : super(key: key);
Добавил

2022-04-01 19:27 UTC, Veselchak-U approved these changes

2022-04-03 23:15 UTC, NeoZ3p approved these changes

2022-04-05 15:58 UTC, dkrutskikh approved these changes

2022-04-05 15:58 UTC, merged