feat: bloc onboarding
boostgrade/wtgt_gamma pull request #81
Opened 2022-04-11 23:11 UTC by NeoZ3p

# Ссылка на задачу
Задача #58

# Что было сделано

- Блок с 2 ивентами: инициализация, при которой идет проверка на прохождение онбоардинга и в зависимости от результата необходимое состояние, а также пропуск онбоардинга.
- Вьюмодель онбоардинга

# Как проверить работу?

- Запустить проект и нажать на кнопку пропуска

# Чек-лист
- [ ] Функциональность протестирована и работает корректно

2022-04-19 08:56 UTC, loopnyapy approved these changes

2022-04-21 07:45 UTC, Veselchak-U requested changes

2022-04-21 07:45 UTC, Veselchak-U commented on lib/src/features/onboard/services/onboarding_bloc.dart
> +  final onboardingStorage = OnboardStorage();
Лишняя строчка.

2022-04-21 07:45 UTC, Veselchak-U commented on lib/src/features/onboard/services/onboarding_bloc.dart
> +      : super(const OnboardingState.loadInProgress()) {
Мне видится что начальное состояние блока должно быть OnboardingState.initial.
Далее (из VM) инициируется событие OnboardingInited, в начале которого уже эмитится OnboardingState.loadInProgress. И в конце обработчика по итогам проверки эмитится одно из двух состояний: "онбоардинг не требуется" (OnboardingState.skipSuccess) или "требуется онбоардинг" (не хватает этого статуса).

2022-04-25 22:43 UTC, NeoZ3p commented on lib/src/features/onboard/services/onboarding_bloc.dart
> +      : super(const OnboardingState.loadInProgress()) {
Не совсем понимаю зачем :о

2022-05-02 09:08 UTC, dkrutskikh approved these changes

2022-05-02 09:09 UTC, merged